name: Exploring Variables and Secrets

on:
  workflow_dispatch:


env:
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME: ahmedgmansour
    IMAGE_NAME: github-actions-nginx    

jobs:
  docker:
    runs-on: ubuntu-24.04
    steps:
    - name: Docker Build
      run: echo docker build -t ${{ env.CONTAINER_REGISTRY }}/$DOCKER_USERNAME/$IMAGE_NAME:latest

    - name: Docker Login
      run: echo docker login --username=$DOCKER_USERNAME --password=${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Publish
      run: echo docker push ${{ env.CONTAINER_REGISTRY }}/$DOCKER_USERNAME/$IMAGE_NAME:latest

  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - name: Docker Run
      run: echo docker run -d -p 8080:80 ${{ env.CONTAINER_REGISTRY }}/$DOCKER_USERNAME/$IMAGE_NAME:latest
