name: my first workflow

on:  
  workflow_dispatch:


jobs: 
    first_job:
        runs-on: ubuntu-24.04 
        steps: 
            - name: welcome message
              run: echo "my first github actions"

            - name: checkout repositry
              uses: actions/checkout@v4
              
            - name: list files
              run: ls -la

            # - name: excute shell script 
            #   run: |
            #     chmod +x bash.sh
            #     ./bash.sh         

            - name: check docker version
              run: docker --version                 