name: my first workflow

on: push

jobs: 
    first_job:
        runs-on: ubuntu-24.04 
        steps: 
            - name: welcome message
              run: echo "my first github actions"
            - name: list files
              run: ls -la
            - name: excute shell script 
              run: |
                chmod +x bash.sh
                ./bash.sh         