name: Exploring Variables and Secrets

on:
  push:

env:
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME: ahmedgmansour
    IMAGE_NAME: boardgame   

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Build
      run: echo docker build -t ${{ env.CONTAINER_REGISTRY }}/$DOCKER_USERNAME/$IMAGE_NAME:latest

    - name: Docker Login
      env:
        DOCKER_PASSWORD: 0101025065Ah@
      run: echo docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

    - name: Docker Publish
      run: echo docker push ${{ env.CONTAINER_REGISTRY }}/$DOCKER_USERNAME/$IMAGE_NAME:latest

  # deploy:
  #   needs: docker
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Docker Run
  #     run: docker run -d -p 8080:80 ${{ env.CONTAINER_REGISTRY }}/$DOCKER_USERNAME/$IMAGE_NAME:latest
